name: KICS Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  kics_scan:
    name: KICS Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: KICS
        uses: checkmarx/kics-action@e01759d524f8abd5bd650d3d5bd4b96d46ebbc1d
        with:
          path: ansible,packer,terraform
          token: ${{ secrets.PAT_TOKEN }}
          output_path: kics_results/
          enable_comments: true
          fail_on: high,medium,critical
      - name: display kics results
        run: |
          cat kics_results/results.json


